version: '3'

volumes:
  database: {}

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=lotto-analyzer-mysql
      - MYSQL_ROOT_PASSWORD=testpassword
    volumes:
      - database:/var/lib/mysql
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db