# Generated by Django 3.0 on 2020-04-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_drwNo', models.PositiveIntegerField(default=0)),
                ('final_drwNo', models.PositiveIntegerField(default=0)),
                ('one', models.PositiveIntegerField(default=0)),
                ('two', models.PositiveIntegerField(default=0)),
                ('three', models.PositiveIntegerField(default=0)),
                ('four', models.PositiveIntegerField(default=0)),
                ('five', models.PositiveIntegerField(default=0)),
                ('six', models.PositiveIntegerField(default=0)),
                ('seven', models.PositiveIntegerField(default=0)),
                ('eight', models.PositiveIntegerField(default=0)),
                ('nine', models.PositiveIntegerField(default=0)),
                ('ten', models.PositiveIntegerField(default=0)),
                ('eleven', models.PositiveIntegerField(default=0)),
                ('twelve', models.PositiveIntegerField(default=0)),
                ('thirteen', models.PositiveIntegerField(default=0)),
                ('fourteen', models.PositiveIntegerField(default=0)),
                ('fifteen', models.PositiveIntegerField(default=0)),
                ('sixteen', models.PositiveIntegerField(default=0)),
                ('seventeen', models.PositiveIntegerField(default=0)),
                ('eighteen', models.PositiveIntegerField(default=0)),
                ('nineteen', models.PositiveIntegerField(default=0)),
                ('twenty', models.PositiveIntegerField(default=0)),
                ('twenty_one', models.PositiveIntegerField(default=0)),
                ('twenty_two', models.PositiveIntegerField(default=0)),
                ('twenty_three', models.PositiveIntegerField(default=0)),
                ('twenty_four', models.PositiveIntegerField(default=0)),
                ('twenty_five', models.PositiveIntegerField(default=0)),
                ('twenty_six', models.PositiveIntegerField(default=0)),
                ('twenty_seven', models.PositiveIntegerField(default=0)),
                ('twenty_eight', models.PositiveIntegerField(default=0)),
                ('twenty_nine', models.PositiveIntegerField(default=0)),
                ('thirty', models.PositiveIntegerField(default=0)),
                ('thirty_one', models.PositiveIntegerField(default=0)),
                ('thirty_two', models.PositiveIntegerField(default=0)),
                ('thirty_three', models.PositiveIntegerField(default=0)),
                ('thirty_four', models.PositiveIntegerField(default=0)),
                ('thirty_five', models.PositiveIntegerField(default=0)),
                ('thirty_six', models.PositiveIntegerField(default=0)),
                ('thirty_seven', models.PositiveIntegerField(default=0)),
                ('thirty_eight', models.PositiveIntegerField(default=0)),
                ('thirty_nine', models.PositiveIntegerField(default=0)),
                ('forty', models.PositiveIntegerField(default=0)),
                ('forty_one', models.PositiveIntegerField(default=0)),
                ('forty_two', models.PositiveIntegerField(default=0)),
                ('forty_three', models.PositiveIntegerField(default=0)),
                ('forty_four', models.PositiveIntegerField(default=0)),
                ('forty_five', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
