# Generated by Django 3.0 on 2020-04-16 08:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20200416_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottocount',
            name='drwNos',
            field=django_mysql.models.SetCharField(models.IntegerField(null=True), max_length=8000, size=8),
        ),
    ]
